### ISSUE TITLE
Cannot resolve the spec for this pod/Cannot resolve this pv

### ISSUE THREAD

**Issue by lukaskane0** [kais271/pvc-exporter#23]
In my k8s deployment 'pvc_usage' metrics for most of PVs doesn't collected. 
I found these errors i pvc-exporter logs
```
block pvc .................
20.0G
Traceback (most recent call last):
  File "./pvc-exporter.py", line 48, in unit_conversion
    get_size=re.match(rex,size).group()
AttributeError: 'NoneType' object has no attribute 'group'
2021-12-15 10:04:46,925 - pvc-exporter - WARNING - Not found expected info for this string: 0
2021-12-15 10:04:46,925 - pvc-exporter - ERROR - Cannot resovle this pv pvc-2f159aad-95ec-4798-930a-ef493cf17bf4
Traceback (most recent call last):
  File "./pvc-exporter.py", line 108, in get_pvc_used
    human_size,MB_size=unit_conversion(returned_fs_info[1])
TypeError: cannot unpack non-iterable NoneType object
2021-12-15 10:04:46,926 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: osm-renderer-5f895899dc-mvr54
Traceback (most recent call last):
  File "./pvc-exporter.py", line 161, in <module>
    pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
  File "./pvc-exporter.py", line 115, in get_pvc_used
    return pvc_used,pvc_used_percent,pvc_type
UnboundLocalError: local variable 'pvc_used' referenced before assignment
block pvc .................
/dev/rbd0
2021-12-15 10:04:47,090 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: elastic-0
Traceback (most recent call last):
  File "./pvc-exporter.py", line 161, in <module>
    pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
  File "./pvc-exporter.py", line 115, in get_pvc_used
    return pvc_used,pvc_used_percent,pvc_type
UnboundLocalError: local variable 'pvc_used' referenced before assignment
```
Using Ceph CSI Provisioner(Cephfs and RBD) and Kubernetes 1.20.7.
Tried both 0.1.3-alpha and  0.1.3-beta pvc-exporter versions 

Also, I have metrics for the one(out of 12) of PV. I cannot find any difference between it and rest of PVs, which doesn't have 'pvc_usage' metric. They are using same provisioner, deployed on the same cluster, and even on the same node..

**Comment by kais271** [comment]
Could you please run 'df  -h' in pvc-exporter pod and share that results to here ? And ,what is host's OS ?

**Comment by lukaskane0** [comment]
Output is quite big, so I attached it as file.
Nodes running on Centos 7, container runtime - CRI-O
```
# uname -r
3.10.0-1160.25.1.el7.x86_64
# crio -v
INFO[0000] Starting CRI-O, version: 1.20.3, git: d5a999ad0a35d895ded554e1e18c142075501a98(clean)
crio version 1.20.3
Version:       1.20.3
GitCommit:     d5a999ad0a35d895ded554e1e18c142075501a98
GitTreeState:  clean
BuildDate:     2021-06-03T20:25:30Z
GoVersion:     go1.15.5
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```
[dfh.txt](https://github.com/kais271/pvc-exporter/files/7725892/dfh.txt)

This output from node, there are single PVC  with metrics(persistentvolume="pvc-454093f2-3dae-4dc8-9226-cd4c19893b45", persistentvolumeclaim="geocoder-data-pvc") mapped, but also another PVCs without metrics mapped too.

**Comment by kais271** [comment]
I know where the problem is, give me some time to fix it.

**Comment by kais271** [comment]
A plan has been scheduled to rewrite the module that obtains disk information to fundamentally solve this problem.
https://github.com/kais271/pvc-exporter/projects/3

**Comment by kais271** [comment]
@lukaskane0  Try to re-pull this image dockerid31415926/pvc-exporter:v0.1.3-beta, I have made some changes.

**Comment by lukaskane0** [comment]
I tried it.
Same errors.
Using image docker.io/dockerid31415926/pvc-exporter@sha256:169a6e5d05dbb670e4c1eb9448ebc20e4c048564921866df2d2b78e7faa39337
Is this latest image?

**Comment by kais271** [comment]
Yes, it's latest. Let me change it again with other methods, please wait for my news.

**Comment by kais271** [comment]
Hi , try this image: `dockerid31415926/pvc-exporter:v0.1.3-beta.rc2`

**Comment by lukaskane0** [comment]
Hi. 
Thanks for your help
I used new image and I can see can metrics for PVs, created by provisioner(ceph-csi, just in case), but for manually created PVs(using local and cephfs storage types) same error are present.
Error example
```
2022-01-10 09:26:18,704 - pvc-exporter - ERROR - Cannot resovle this pv mongo-pv2
Traceback (most recent call last):
  File "//./pvc-exporter.py", line 123, in get_pvc_used
    raise
RuntimeError: No active exception to reraise
2022-01-10 09:26:18,705 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: mongo-1
Traceback (most recent call last):
  File "//./pvc-exporter.py", line 184, in <module>
    pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
  File "//./pvc-exporter.py", line 131, in get_pvc_used
    return pvc_used,pvc_used_percent,pvc_type
UnboundLocalError: local variable 'pvc_used' referenced before assignment
2022-01-10 09:26:19,498 - pvc-exporter - ERROR - Cannot resovle this pv registry-pv
Traceback (most recent call last):
  File "//./pvc-exporter.py", line 123, in get_pvc_used
    raise
RuntimeError: No active exception to reraise
2022-01-10 09:26:19,498 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: registry-76b44cddf4-vvnxq
Traceback (most recent call last):
  File "//./pvc-exporter.py", line 184, in <module>
    pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
  File "//./pvc-exporter.py", line 131, in get_pvc_used
    return pvc_used,pvc_used_percent,pvc_type
UnboundLocalError: local variable 'pvc_used' referenced before assignment
2022-01-10 09:26:19,498 - pvc-exporter - INFO - Will sleep ...
```
There are some manifest examples for PVs without metrics
Cephfs PV 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2021-02-16T14:12:16Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: registry-pv
  resourceVersion: "2678022"
  selfLink: /api/v1/persistentvolumes/registry-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  cephfs:
    monitors:
    - 10.252.253.215:6789
    - 10.252.253.216:6789
    - 10.252.253.217:6789
    path: /pvc-volumes/registry
    secretRef:
      name: ceph-admin-secret
      namespace: kube-system
    user: admin
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: registry-pvc
    namespace: registry
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cephfs-manual
  volumeMode: Filesystem
status:
  phase: Bound
```
Cephfs PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2021-02-16T14:12:16Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: registry-pvc
  namespace: registry
  resourceVersion: "2678062"
  selfLink: /api/v1/namespaces/registry/persistentvolumeclaims/registry-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: cephfs-manual
  volumeMode: Filesystem
  volumeName: registry-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  phase: Bound
```
Local PV
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: mongo
  name: mongo-pv2
  resourceVersion: "3269598"
  selfLink: /api/v1/persistentvolumes/mongo-pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-mongo-1
    namespace: default
  local:
    path: /data/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master5
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Bound
```
Local PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mongo
  resourceVersion: "3269600"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/data-mongo-1
  name: data-mongo-1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: mongo-pv2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
```
If you need any additional info, please, tell me.
And thanks again.

**Comment by kais271** [comment]
You are welcome. 
What version is your k8s?

**Comment by kais271** [comment]
@lukaskane0 
I think that error is caused by duplicate pvc name, you can check it if you have time.
I need a few days to fix it.

**Comment by lukaskane0** [comment]
v1.20.7

**Comment by kais271** [comment]
@lukaskane0 
Try this `dockerid31415926/pvc-exporter:v0.1.3-beta.rc3.2 ` . If this image cannot resovle registry-pvc, please share /etc/mtab on the node where the registry-pvc is located.

**Comment by kais271** [comment]
And, for that image. I have changed grafana query. 
This is new:
`(sum without (grafana_key ) ((sum without (container,pod,service,namespace,job,instance,endpoint,pvc_namespace,pvc_requested_size_MB) (pvc_usage)) + on(grafana_key) group_left(persistentvolumeclaim,mountedby,pod_namespace)pvc_mapping{pod_namespace=~"$pod_namespace",mountedby=~"$Pod"}*0))`

**Comment by lukaskane0** [comment]
Sorry for the long waiting - doesn't have enough time to check it.
But, finally, I checked last version you provided, that all metric works fine(even on manuallu created PVs), except for pod on the one of nodes.  
Errors are looks like this
```
pvc-exporter ERROR Cannot resolve the spec for this pod: api-engine-d7bf74955-n7z7p
pvc-exporter ERROR Cannot resolve the spec for this pod: geoserver-5d7bd6d49-l7qwr
pvc-exporter ERROR Cannot resolve the spec for this pod: osm-renderer-5f895899dc-frpbt
pvc-exporter ERROR Cannot resolve the spec for this pod: osm-renderer-5f895899dc-h4t95
pvc-exporter ERROR Cannot resolve the spec for this pod: osm-renderer-5f895899dc-kxdng
pvc-exporter ERROR Cannot resovle this pv pvc-2f159aad-95ec-4798-930a-ef493cf17bf4
pvc-exporter ERROR Cannot resovle this pv pvc-84c4e2a9-6dab-4c0c-b8ea-bf2ac473bb0c
```
All this pods are on the same node. /etc/mtab from this node are attached below 
[mtab.txt](https://github.com/kais271/pvc-exporter/files/7924841/mtab.txt)

**Comment by kais271** [comment]
Thanks for your question to make this metric even better.
I plan to solve this problem next week, some busy recently.

**Comment by kais271** [comment]
@lukaskane0  hi, try this version: dockerid31415926/pvc-exporter:v0.1.3-0209

**Comment by lukaskane0** [comment]
Hello. 
I checked this version. All metrics are present, for all type of pv's. There are no any errors in logs.  So, I'm closing this issue. Thanks, @kais271 !
PS. Waiting for final 0.1.3 version 👍
