### ISSUE TITLE
Error on not ready PODs with 0.1.3-rc

### ISSUE THREAD

**Issue by davidhrbac** [kais271/pvc-exporter#24]
```console
2022-01-21 14:03:06,834 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: chronos-backup-job-1642384800-n5dkb
Traceback (most recent call last):
File "//./pvc-exporter.py", line 187, in <module>
pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
File "//./pvc-exporter.py", line 103, in get_pvc_used
pvc_used,pvc_used_percent=calculate_size(fs_path,total_MB_size,pvc_type)
UnboundLocalError: local variable 'fs_path' referenced before assignment
2022-01-21 14:03:06,863 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: chronos-backup-job-1642471200-5fk8t
Traceback (most recent call last):
File "//./pvc-exporter.py", line 187, in <module>
pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
File "//./pvc-exporter.py", line 103, in get_pvc_used
pvc_used,pvc_used_percent=calculate_size(fs_path,total_MB_size,pvc_type)
UnboundLocalError: local variable 'fs_path' referenced before assignment

08 - pvc-exporter - INFO - Found --> NS: infra-minio, PVC: minio, PV: pvc-8f35d732-27b8-44b5-95cd-3f17a9b0d98d, PVC_TYPE: nfs, POD: minio-5cdb664749-x98pq, HOST_IP: 10.93.128.213, SIZE: 35840.0, USED: 1500, PERCENT: 0.05
2022-01-21 14:05:39,792 - pvc-exporter - INFO - Found --> NS: infra-rabbitmq, PVC: data-rabbitmq-ha-0, PV: pvc-c00aec75-2235-40f7-a47c-e4299a76bf84, PVC_TYPE: nfs, POD: rabbitmq-ha-0, HOST_IP: 10.93.128.213, SIZE: 8192.0, USED: 318, PERCENT: 0.05
```

**Comment by kais271** [comment]
Hi , this‘s know issue, but it doesn't affect functionality. I'll handle this situation gracefully in the next PR.

**Comment by kais271** [comment]
@davidhrbac Hi ，please try re-pull 0.1.3-rc, I made some changes. The latest sha256:c7f00e287d2cc15256176ba04a5c3836dc6e55e5d7648dab58842d7ac39dc12d

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.

**Comment by davidhrbac** [comment]
Sorry to reply today, 0.1.3-rc is OK! Thanks!
